### PR TITLE
Fixes: #44

### LINKED ISSUE #44: Add program to return sum of digits in integers.
There are quite a few methods to do this.
Implement all of them with a different name.
Add proper docs on how the program works.

### PR DESCRIPTION
**Pull request by AkMo3**
### **Describe your change:**

- [ ] Add an Algorithm?
- [ ] Add a Data Structure?
- [x] Add a Program not related to above?
- [ ] Fix a bug or typo in an existing cases?
- [ ] Documentation change?

#### References

Closes #44 

### **Checklist:**

- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

### CODE REVIEW

File: NumberSystem/SumOfDigits.java [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+
+  /**
+   * Computes the sum of digits of a integer through recursion.
+   *
+   * @param n Integer whose sum of digits is to be returned.
+   * @return Sum of digits of Integer
+   */
+  public static int digitSumRecursion(long n) {
+    n = Math.abs(n);
+    return n < 10 ? (int) n : (int) (n + digitSumRecursion(n / 10));
```
Comment (AkMo3) [inline NumberSystem/SumOfDigits.java]: The remainder of number divided by 10 is to be added not n
